[package]
name = "MyNKF"
version = "1.6.1"
edition = "2024"

[lib]
name = "mynkf"
path = "src/lib.rs"

[[bin]]
name = "mynkf"
path = "src/main.rs"

[dependencies]
# 共有ライブラリの参照追加
common_lib = { path = "../common_lib" }

[profile.release]
opt-level = 'z'       # Optimize for binary size
lto = true            # Link-Time Optimization
codegen-units = 1     # Integrate code generation units
panic = 'abort'       # Abort on panic to save space
strip = true          # Strip symbols and debug info

